version: '3.7'

# define network name
networks:
  laravel:

# keep database event when container is down
volumes:
  mariadb_data:
    driver: local

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      # map local port 8080 to container port 80
      - "8080:80"
    volumes:
      - type: bind
        source: ./nginx/conf/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ../../app-name
        target: /var/www
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      # will start php and mysql service before starting
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - ./mariadb_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ../../app-name:/var/www
    working_dir: /var/www
    ports:
      - '9091:9000'
    environment:
      PHP_MEMORY_LIMIT: 1G
    networks:
      - laravel
